dataset: cifar10
model_name: resnet18_cifar      # CIFAR variant (3×3 conv1, no maxpool)
data_dir: ./data

# training
batch_size: 128
epochs: 40
lr: 0.001
weight_decay: 0.0005
num_workers: 2
seed: 41
device: auto

# image + normalization (CIFAR-10 stats)
img_size: 32
mean: [0.4914, 0.4822, 0.4465]
std:  [0.2470, 0.2435, 0.2616]

# logging+artifacts
log_root: runs
ckpt_root: checkpoints
reports_root: reports

early_stop:
  monitor: val_loss
  mode: min
  patience: 5
  min_delta: 0.0
