dataset: cifar10
model_name: resnet18_imagenet   # ImageNet-pretrained; resize to 224
data_dir: ./data

batch_size: 128
epochs: 20
lr: 0.0005
weight_decay: 0.0005
num_workers: 2
seed: 41
device: auto

# image + normalization (ImageNet stats)
img_size: 224
mean: [0.485, 0.456, 0.406]
std:  [0.229, 0.224, 0.225]

log_root: runs
ckpt_root: checkpoints
reports_root: reports

early_stop:
  monitor: val_loss
  mode: min
  patience: 5
  min_delta: 0.0
